# Concatenation and Split

In [1]:
import numpy as np

In [10]:
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)
arr3 = np.arange(33, 49).reshape(4,4)

In [11]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [12]:
# manual row wise concatenation
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [13]:
# vertical concatenation
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [14]:
# horizontal concatenation
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [15]:
np.hstack((arr1, arr2, arr3))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 33, 34, 35, 36],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 37, 38, 39, 40],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 41, 42, 43, 44],
       [13, 14, 15, 16, 29, 30, 31, 32, 45, 46, 47, 48]])

In [19]:
# it splits the array and stores it in a list
arr = np.split(arr1, 2)
arr

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [21]:
type(arr)

list

In [22]:
type(arr[0])

numpy.ndarray

In [24]:
# row wise splitting

np.split(arr1, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [25]:
d1 = np.array([1,2,3,4,5,6,7])
np.split(d1, [1,3])

[array([1]), array([2, 3]), array([4, 5, 6, 7])]