In [1]:
import numpy as np

In [2]:
mx_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
mx_1s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
mx_1s.dtype

dtype('int32')

In [5]:
mx_1s = np.ones(5)
mx_1s

array([1., 1., 1., 1., 1.])

In [6]:
mx_1s.dtype

dtype('float64')

In [8]:
mx_1s = np.ones((5,5))
mx_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
mx_1s = np.ones((4,3), dtype=int)
mx_1s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
mx_1s.dtype

dtype('int32')

In [13]:
mx_0s = np.zeros((4,3))
mx_0s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
mx_0s = np.zeros((4,3), dtype=bool)
mx_0s

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
mx_0s = np.zeros((4,3), dtype=str)
mx_0s

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [16]:
em_mx = np.empty((3,3))
em_mx

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.82e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])