# Random Sampling with Numpy

In [6]:
import numpy as np
import random

In [7]:
np.random.random(2)

array([0.04803265, 0.49689756])

In [9]:
# creating 2-d array using random function

np.random.random((3,3))

array([[0.8182715 , 0.22590589, 0.80540206],
       [0.32449211, 0.84659083, 0.27397715],
       [0.9596207 , 0.84471476, 0.3121451 ]])

In [11]:

np.random.randint(1,4)

2

In [12]:
# creating 2-d array using random function of int type

np.random.randint(1,4, (4,4))

array([[2, 3, 1, 2],
       [2, 2, 1, 3],
       [1, 1, 3, 3],
       [3, 1, 3, 3]])

In [17]:
# creating 3-d array using random function of int type

np.random.randint(1,4, (2,4,4))

array([[[3, 1, 1, 1],
        [3, 1, 2, 2],
        [1, 1, 1, 1],
        [3, 1, 1, 1]],

       [[1, 2, 1, 1],
        [2, 2, 3, 2],
        [3, 2, 1, 1],
        [1, 2, 2, 3]]])

In [18]:
# creating 3-d array using random function of int type with non-changeble values
# seed function has (2**32 -1) patterns

np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [19]:
# the output values will be in zeros only
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [20]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [21]:
# negative and positive values used for standard and normal distribution
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [24]:
x = [1,2,3,4]
for i in range(10):
    print(np.random.choice(x))

2
3
3
4
1
1
1
1
3
3


In [25]:
np.random.permutation(x)

array([1, 3, 4, 2])

In [26]:
np.random.permutation(x)

array([2, 3, 4, 1])